"""Tests for the byte-deterministic ``rebac build-zed`` emitter.

Per CLAUDE.md § 6: ``effective.zed`` MUST be byte-identical across runs,
machines, Python versions and Django versions. These tests are the CI gate
that catches non-determinism — re-ordered relations / definitions / caveats
in any source ``permissions.zed`` must NOT change a single byte of output.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

import pytest

from rebac import __version__
from rebac.management.commands.rebac import Command as RebacCommand


@pytest.fixture
def stub_app(tmp_path: Path):
    """Build a fake AppConfig pointing at a tmp permissions.zed file."""

    class _StubAppConfig:
        def __init__(self, name: str, schema_text: str, label: str) -> None:
            app_dir = tmp_path / label
            app_dir.mkdir()
            (app_dir / "permissions.zed").write_text(schema_text, encoding="utf-8")
            self.name = name
            self.label = label
            self.path = str(app_dir)
            self.rebac_schema = "permissions.zed"

    return _StubAppConfig


def _run_build(monkeypatch: pytest.MonkeyPatch, app_configs: list[Any], out: Path) -> str:
    """Invoke ``rebac build-zed --out`` against a curated AppConfig list.

    We instantiate the ``Command`` directly rather than going through
    ``call_command``: the latter resolves a command name against the
    installed-apps registry, which we are deliberately monkeypatching for
    these tests.
    """
    monkeypatch.setattr(
        "rebac.management.commands.rebac.apps.get_app_configs",
        lambda: list(app_configs),
    )
    cmd = RebacCommand()
    cmd._handle_build_zed({"out": str(out)})
    return out.read_text(encoding="utf-8")


SCHEMA_A = """\
// @rebac_package: blog
// metadata comment that must be stripped
definition blog/post {
    relation owner: auth/user
    relation viewer: auth/user | auth/group#member | auth/user:*

    permission read = owner + viewer
    permission write = owner
}
"""

SCHEMA_B = """\
// @rebac_package: drive
definition drive/file {
    relation parent: drive/folder
    relation owner: auth/user

    permission read = owner + parent->read
    permission write = owner - parent->banned
}

caveat ip_in_cidr(ip ipaddress, cidr string) {
    ip.in_cidr(cidr)
}
"""

# Same schemas with definitions / relations / permissions in *different* source
# order. The deterministic emitter must produce byte-identical output regardless
# of how the author chose to order things in the .zed file.
SCHEMA_A_REORDERED = """\
// @rebac_package: blog
definition blog/post {
    permission write = owner
    permission read = owner + viewer

    relation viewer: auth/user:* | auth/group#member | auth/user
    relation owner: auth/user
}
"""

SCHEMA_B_REORDERED = """\
// @rebac_package: drive
caveat ip_in_cidr(ip ipaddress, cidr string) {
    ip.in_cidr(cidr)
}

definition drive/file {
    permission write = owner - parent->banned
    permission read = owner + parent->read

    relation owner: auth/user
    relation parent: drive/folder
}
"""


def test_build_zed_is_byte_deterministic(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, stub_app: Any
) -> None:
    """Running build-zed twice into separate tmpdirs yields identical bytes."""
    out1_dir = tmp_path / "run1"
    out2_dir = tmp_path / "run2"
    out1_dir.mkdir()
    out2_dir.mkdir()
    out1 = out1_dir / "effective.zed"
    out2 = out2_dir / "effective.zed"

    apps_a = [
        stub_app(name="acme.blog", schema_text=SCHEMA_A, label="blog_run1"),
        stub_app(name="acme.drive", schema_text=SCHEMA_B, label="drive_run1"),
    ]
    text1 = _run_build(monkeypatch, apps_a, out1)

    apps_b = [
        stub_app(name="acme.blog", schema_text=SCHEMA_A, label="blog_run2"),
        stub_app(name="acme.drive", schema_text=SCHEMA_B, label="drive_run2"),
    ]
    text2 = _run_build(monkeypatch, apps_b, out2)

    assert text1 == text2
    # Belt-and-braces: byte-level equality at the file boundary too.
    assert out1.read_bytes() == out2.read_bytes()


def test_build_zed_header_shape(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, stub_app: Any
) -> None:
    """Header is exactly three lines: generator stamp, content_hash, use typechecking."""
    out = tmp_path / "effective.zed"
    apps_list = [stub_app(name="acme.blog", schema_text=SCHEMA_A, label="blog")]
    text = _run_build(monkeypatch, apps_list, out)

    lines = text.split("\n")
    assert lines[0] == f"// Generated by django-zed-rebac {__version__}"
    assert lines[1].startswith("// content_hash: ")
    # The hash is a 64-char lowercase hex sha256.
    digest = lines[1].removeprefix("// content_hash: ")
    assert len(digest) == 64
    assert all(ch in "0123456789abcdef" for ch in digest)
    assert lines[2] == "use typechecking"

    # The recorded hash MUST be sha256 of the body that follows the header.
    body = text.split("use typechecking\n", 1)[1]
    assert hashlib.sha256(body.encode("utf-8")).hexdigest() == digest

    # File ends in a newline.
    assert text.endswith("\n")
    # Strict LF — no CR-injected line endings on any platform.
    assert "\r" not in text


def test_build_zed_sort_independent(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, stub_app: Any
) -> None:
    """Re-ordered relations / permissions / definitions yield identical output."""
    out_natural = tmp_path / "natural" / "effective.zed"
    out_natural.parent.mkdir()
    out_reordered = tmp_path / "reordered" / "effective.zed"
    out_reordered.parent.mkdir()

    natural_apps = [
        stub_app(name="acme.blog", schema_text=SCHEMA_A, label="blog_n"),
        stub_app(name="acme.drive", schema_text=SCHEMA_B, label="drive_n"),
    ]
    reordered_apps = [
        stub_app(name="acme.drive", schema_text=SCHEMA_B_REORDERED, label="drive_r"),
        stub_app(name="acme.blog", schema_text=SCHEMA_A_REORDERED, label="blog_r"),
    ]

    text_natural = _run_build(monkeypatch, natural_apps, out_natural)
    text_reordered = _run_build(monkeypatch, reordered_apps, out_reordered)

    assert text_natural == text_reordered
    # Sanity: definitions appear alphabetically (blog/post before drive/file).
    blog_idx = text_natural.index("definition blog/post")
    drive_idx = text_natural.index("definition drive/file")
    assert blog_idx < drive_idx
    # Sanity: source `// @rebac_*` headers and inline comments are stripped.
    assert "@rebac_package" not in text_natural
    assert "metadata comment" not in text_natural
    # Sanity: compound expressions are parenthesised (CLAUDE.md § 7).
    # `owner + parent->read` becomes `(owner + parent->read)`.
    assert "(owner + parent->read)" in text_natural
    # `owner - parent->banned` preserves LHS / RHS for the non-commutative `-`.
    assert "(owner - parent->banned)" in text_natural
